# Generated by Django 6.0.2 on 2026-02-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('club_function', 'Club Function'), ('club_hire_bar', 'Club Hire with Bar'), ('club_hire_no_bar', 'Club Hire without Bar'), ('working_bee', 'Working Bee'), ('other', 'Other')], default='club_function', max_length=30)),
                ('is_approved', models.BooleanField(default=True, help_text='Approval flag — Event Officer can toggle. Types requiring approval default to False.')),
                ('start_datetime', models.DateTimeField(db_index=True)),
                ('end_datetime', models.DateTimeField()),
                ('contact_name', models.CharField(blank=True, default='', max_length=100)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'events_event',
                'ordering': ['start_datetime'],
            },
        ),
    ]
