# Generated by Django 6.0.2 on 2026-02-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventcategory_remove_event_event_type_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Approval flag — categories with requires_approval default to False on creation.'),
        ),
    ]
