# Generated by Django 6.0.2 on 2026-02-27 23:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_update_is_approved_help_text'),
        ('roster', '0003_merge_staff_into_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bar_staff_users',
            field=models.ManyToManyField(blank=True, help_text='1-4 RSA-certified bar staff assigned to this event', related_name='bar_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='bar_staff',
            field=models.ManyToManyField(blank=True, help_text='LEGACY: being migrated to bar_staff_users', related_name='events', to='roster.staffmember'),
        ),
    ]
