# Generated by Django 6.0.2 on 2026-03-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_swap_bar_staff_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='licence_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='licence_obtained',
            field=models.BooleanField(default=False),
        ),
    ]
