# Generated by Django 6.0.2 on 2026-02-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_admin_club',
            field=models.BooleanField(default=False, help_text='Can administer events and roster'),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, choices=[('commodore', 'Commodore'), ('vice_commodore', 'Vice-Commodore'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('events_officer', 'Events Officer')], default='', help_text='Honorary committee title (display only, does not control access)', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_event_officer',
            field=models.BooleanField(default=False, help_text='Can approve/reject/delete events'),
        ),
    ]
