# Generated by Django 6.0.2 on 2026-02-28 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_old_role_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin_level',
            field=models.CharField(blank=True, choices=[('', 'None'), ('event_officer', 'Events Officer'), ('secretary', 'Secretary')], default='', help_text='Secretary: full admin. Event Officer: roster + events.', max_length=20),
        ),
    ]
