# Generated by Django 6.0.2 on 2026-02-18 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RosterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_date', models.DateField(help_text='A known Friday where the rotation position is established')),
                ('anchor_staff_position', models.PositiveIntegerField(default=1, help_text='The staff position number assigned to anchor_date')),
            ],
            options={
                'db_table': 'roster_config',
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('position', models.PositiveIntegerField(help_text='Order in the rotation cycle (1-based)')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive staff are excluded from rotation but kept for history')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'roster_staff',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='RosterDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('source', models.CharField(choices=[('rotation', 'Friday Rotation Override'), ('event', 'Special Event')], default='rotation', max_length=20)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, help_text='Set when source=event', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roster_assignments', to='events.event')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_dates', to='roster.staffmember')),
            ],
            options={
                'db_table': 'roster_dates',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date', 'source'], name='roster_date_date_9bb46b_idx')],
            },
        ),
    ]
