# Generated by Django 6.0.2 on 2026-02-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0005_add_is_override_and_populate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rosterdate',
            name='source',
            field=models.CharField(choices=[('rotation', 'Rotation'), ('event', 'Special Event')], default='rotation', max_length=20),
        ),
    ]
